# .github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        

      - name: Install runtime + dev dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt          # runtime (scipy, streamlit …)
          pip install flake8 black isort pytest    # dev / QA tools
          pip install -e .                         # make `src` importablepip install -r requirements.txt   


      # ------- quality gates ----------
      - name: Lint
        run: flake8 src tests --max-line-length 100

      - name: Test
        run: pytest -q
